/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'dpp' at '12/21/16 10:50 AM' with Gradle 3.2.1
 *
 * @author dpp, @date 12/21/16 10:50 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
