/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'dpp' at '12/21/16 10:51 AM' with Gradle 3.2.1
 *
 * @author dpp, @date 12/21/16 10:51 AM
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
