/*
 * This Spock specification was auto generated by running the Gradle 'init' task
 * by 'dpp' at '12/21/16 10:51 AM' with Gradle 3.2.1
 *
 * @author dpp, @date 12/21/16 10:51 AM
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
