---
apiVersion: v1
kind: Service
metadata:
  name: funcatron-rabbit
  labels:
    app: funcatron-rabbit
spec:
  ports:
    - name: stomp
      port: 61613
    - name: rabbit
      port: 5672
    - name: rabbitadm
      port: 15672
  type: ClusterIP
  selector:
    app: funcatron-rabbit
