---
apiVersion: v1
kind: Service
metadata:
  name: funcatron-runner
  labels:
    app: funcatron-runner
spec:
  ports:
    - name: http
      port: 3000
  type: ClusterIP
  selector:
    app: funcatron-runner
